USE [ACQ_WEDABAY]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[DASH_ASSAY_OUT] AS (SELECT [ACQ_WEDABAY].[dbo].[SAMPLE].[HOLEID],
      [ACQ_WEDABAY].[dbo].[SAMPLE].[SAMPLEID],
	  [ACQ_WEDABAY].[dbo].[CORPSAMPLEASSAY].[NAME],
      [ACQ_WEDABAY].[dbo].[CORPSAMPLEASSAY].[PRIORITY],
      [ACQ_WEDABAY].[dbo].[CORPSAMPLEASSAY].[VALUE]
FROM [ACQ_WEDABAY].[dbo].[SAMPLE], [ACQ_WEDABAY].[dbo].[CORPSAMPLEASSAY]
WHERE [ACQ_WEDABAY].[dbo].[SAMPLE].[SAMPLEID] = [ACQ_WEDABAY].[dbo].[CORPSAMPLEASSAY].SAMPLEID
AND [ACQ_WEDABAY].[dbo].[CORPSAMPLEASSAY].[NAME] = 'MgO_XRF_pct'
AND [ACQ_WEDABAY].[dbo].[CORPSAMPLEASSAY].[VALUE] IS NOT NULL)
GO


